language: csharp
mono: none
dotnet: 3.1.100
git:
  depth: false
sudo: required

addons:
  sonarcloud:
    organization: "chuckfork"
    
before_install:
- bash ./tools/travis-ci-install-sonar.sh

install:
- dotnet restore SuperSocket.sln

script:
    - dotnet build
    - cd samples
    - dotnet build
    - cd ../test/Test
    - dotnet test
    - bash ./tools/travis-ci-build.sh
global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1